- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity # Frontier JobHeadOfSecurity<JobHeadOfSecurityOld
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 3600 #1 hr
    - !type:RoleTimeRequirement
      role: JobDetective
      time: 3600 #1 hr, knowing how to use the tools is important
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 18000 #5 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # 10 hrs
  weight: 10
  startingGear: HoSGear
  icon: "JobIconHeadOfSecurity"
  supervisors: job-supervisors-captain
  # canBeAntag: false
  ## Frontier: commented out stuff below
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  ## Frontier: commented out stuff above
  setPreference: true
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: HoSGear
  equipment:
#    eyes: ClothingEyesGlassesSecurity # HL - Add departmental NF-style loadouts
    id: HoSPDA
#    gloves: ClothingHandsGlovesCombat # HL - Add departmental NF-style loadouts
    ears: ClothingHeadsetAltSecurity
    pocket1: NFWeaponPistolMk58 # Frontier: use NF version
  storage:
    back:
    - Flash
    - Magazine45_ACPPistolFMJ
