# Base prototypes can be found in \Resources\Prototypes\Recipes\Lathes\security.yml
#region Base
- type: latheRecipe
  id: BaseEmptyMagazineRecipe
  abstract: true
  categories:
  - Magazines
  completetime: 1

- type: latheRecipe
  id: BaseFilledMagazineRecipe
  parent: BaseEmptyMagazineRecipe
  abstract: true
  completetime: 2.5

#region Xbow Bolts
- type: latheRecipe # crossbow bolt
  id: CrossbowBolt
  parent: BaseAmmoRecipe
  result: CrossbowBolt
  materials:
    Steel: 20

- type: latheRecipe # crossbow bolt
  id: CrossbowBoltBroadhead
  parent: BaseAmmoRecipe
  result: CrossbowBoltBroadhead
  materials:
    Steel: 25

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponPistolPollock
  result: WeaponPistolPollock
  completetime: 3
  materials:
    Steel: 1000
    Plastic: 1200
    Plasteel: 1200

#- type: latheRecipe
#  parent: WeaponEnergyPistolDisabler # Frontier: WeaponDisabler<WeaponEnergyPistolDisabler
#  id: WeaponEnergySubMachineGunDisabler # Frontier: WeaponDisablerSMG<WeaponEnergySubMachineGunDisabler
#  result: WeaponEnergySubMachineGunDisabler # Frontier: WeaponDisablerSMG<WeaponEnergySubMachineGunDisabler
#  materials:
#    Steel: 1000
#    Glass: 500
#    Plastic: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponEnergyPistolLaserSvalinn
  result: WeaponLaserSvalinn
  materials:
    Steel: 2000
    Gold: 500

# region Grenades
#- type: latheRecipe
#  id: MagazineGrenadeEmpty # Frontier: add  prefix
#  result: MagazineGrenadeEmpty # Frontier: add  prefix
#  completetime: 3
#  materials:
#    Steel: 150
#    Plastic: 50

# region Misc
- type: latheRecipe
  id: ClothingEyesHudNfsd
  parent: ClothingEyesHudSecurity
  result: ClothingEyesHudNfsd

- type: latheRecipe
  id: HoloprojectorNfsd
  parent: ClothingEyesHudSecurity
  result: HoloprojectorNfsdEmpty

# region Upstream Removed
