# Base prototypes can be found in \Resources\Prototypes\Recipes\Lathes\security.yml
#region Base
- type: latheRecipe
  id: BaseEmptyMagazineRecipe
  abstract: true
  categories:
  - Magazines
  completetime: 1

- type: latheRecipe
  id: BaseFilledMagazineRecipe
  parent: BaseEmptyMagazineRecipe
  abstract: true
  completetime: 2.5

#region Xbow Bolts
- type: latheRecipe # crossbow bolt
  id: CrossbowBolt
  parent: BaseAmmoRecipe
  result: CrossbowBolt
  materials:
    Steel: 20

- type: latheRecipe # crossbow bolt
  id: CrossbowBoltBroadhead
  parent: BaseAmmoRecipe
  result: CrossbowBoltBroadhead
  materials:
    Steel: 25

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponPistolPollock
  result: WeaponPistolPollock
  completetime: 3
  materials:
    Steel: 1000
    Plastic: 1200
    Plasteel: 1200

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponEnergyRifleCarbinePractice
  result: WeaponEnergyRifleCarbinePractice
  completetime: 6
  materials:
    Steel: 1800
    Glass: 400
    Plastic: 250

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponEnergyRifleCarbine
  result: WeaponEnergyRifleCarbine
  completetime: 6
  materials:
    Steel: 2000
    Glass: 800
    Plastic: 500

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponEnergyPistolDisablerPractice
  result: WeaponEnergyPistolDisablerPractice
  completetime: 4
  materials:
    Steel: 500
    Glass: 100
    Plastic: 200

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponEnergyPistolDisabler
  result: WeaponEnergyPistolDisabler
  completetime: 6
  materials:
    Steel: 500
    Glass: 200
    Plastic: 400

#- type: latheRecipe
#  parent: WeaponEnergyPistolDisabler # Frontier: WeaponDisabler<WeaponEnergyPistolDisabler
#  id: WeaponEnergySubMachineGunDisabler # Frontier: WeaponDisablerSMG<WeaponEnergySubMachineGunDisabler
#  result: WeaponEnergySubMachineGunDisabler # Frontier: WeaponDisablerSMG<WeaponEnergySubMachineGunDisabler
#  materials:
#    Steel: 1000
#    Glass: 500
#    Plastic: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponEnergyPistolLaserAdvanced
  result: WeaponEnergyPistolLaserAdvanced
  materials:
    Steel: 1500
    Glass: 1000
    Gold: 850

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponEnergyRifleSniperCannon
  result: WeaponEnergyRifleSniperCannon
  materials:
    Steel: 1250
    Plastic: 750
    Gold: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponEnergyPistolLaserSvalinn
  result: WeaponLaserSvalinn
  materials:
    Steel: 2000
    Gold: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponEnergyRifleSniperXrayCannon
  result: WeaponEnergyRifleSniperXrayCannon
  materials:
    Steel: 1500
    Glass: 500
    Plastic: 250
    Gold: 100

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponEnergyRifleTemperature
  result: WeaponEnergyRifleTemperature
  materials:
    Steel: 2000
    Glass: 500
    Plastic: 500
    Gold: 500

# region Grenades
#- type: latheRecipe
#  id: MagazineGrenadeEmpty # Frontier: add  prefix
#  result: MagazineGrenadeEmpty # Frontier: add  prefix
#  completetime: 3
#  materials:
#    Steel: 150
#    Plastic: 50

- type: latheRecipe
  id: GrenadeEMP # Frontier: add  prefix
  result: GrenadeEMP # Frontier: add  prefix
  completetime: 3
  materials:
    Steel: 150
    Plastic: 100
    Glass: 20

- type: latheRecipe
  id: GrenadeBlast # Frontier: add  prefix
  result: GrenadeBlast # Frontier: add  prefix
  completetime: 3
  materials:
    Steel: 450
    Plastic: 300
    Gold: 150

- type: latheRecipe
  id: GrenadeFlash
  result: GrenadeFlash
  completetime: 3
  materials:
    Steel: 150
    Plastic: 100
    Glass: 20

# region Misc
- type: latheRecipe
  id: ClothingEyesHudNfsd
  parent: ClothingEyesHudSecurity
  result: ClothingEyesHudNfsd

- type: latheRecipe
  id: HoloprojectorNfsd
  parent: ClothingEyesHudSecurity
  result: HoloprojectorNfsdEmpty

# region Upstream Removed
